# languages.py

LANG_DICT = {
    'id': {
        'welcome': "\n[ Pengelolaan Daftar Tugas Berbasis STACK ]",
        'menu_title': "=== MENU TASK MANAGER ===",
        'menu_insert': "1. Tambah Tugas",
        'menu_update': "2. Perbarui Tugas",
        'menu_delete': "3. Hapus Tugas",
        'menu_search': "4. Cari Tugas",
        'menu_show': "5. Tampilkan Semua Tugas",
        'menu_pop': "6. Pop Tugas Terakhir (LIFO)",
        'menu_exit': "0. Keluar",
        'input_choice': "Pilih menu: ",
        'insert_task_title': "\n-- Tambah Tugas Baru --",
        'task_title': "Judul tugas: ",
        'task_due': "Due date (cth: DD-MM-YYYY): ",
        'task_priority': "Prioritas (Low/Medium/High): ",
        'task_desc': "Deskripsi tugas: ",  # Tambahan
        'task_added': "Tugas '{}' berhasil ditambahkan.",
        'motivation': "Motivasi: ",
        'empty_cannot_update': "Daftar tugas kosong, tidak bisa update.",
        'update_title': "\n-- Perbarui Tugas --",
        'input_index_update': "Masukkan indeks tugas yang ingin diperbarui: ",
        'input_index_invalid': "Input tidak valid. Mohon masukkan angka untuk indeks.",
        'task_updated': "Tugas berhasil diperbarui.",
        'index_invalid': "Indeks tidak valid.",
        'delete_title': "\n-- Hapus Tugas --",
        'input_index_delete': "Masukkan indeks tugas yang ingin dihapus: ",
        'task_deleted': "Tugas berhasil dihapus.",
        'search_title': "\n-- Cari Tugas --",
        'input_search': "Masukkan kata kunci (cari di 'title' atau 'due_date'): ",
        'search_result': "Hasil pencarian:",
        'search_none': "Tidak ada tugas yang cocok dengan keyword tersebut.",
        'show_all': "\n-- Daftar Semua Tugas --",
        'pop_success': "Tugas '{}' berhasil di-pop dari stack.",
        'pop_empty': "Stack kosong, tidak ada yang di-pop.",
        'exit_program': "Keluar dari program. Semoga harimu menyenangkan!",
        'menu_invalid': "Menu tidak valid. Silakan pilih kembali.",
        'index': "No",                # Diganti label "No" (nomor)
        'title': "Judul",
        'due_date': "Batas Waktu",
        'priority': "Prioritas",
        'desc': "Deskripsi",          # Tambahan
        'no_tasks': "Tidak ada tugas dalam daftar."
    },
    'en': {
        'welcome': "\n[ Stack-Based Task Management ]",
        'menu_title': "=== TASK MANAGER MENU ===",
        'menu_insert': "1. Insert Task",
        'menu_update': "2. Update Task",
        'menu_delete': "3. Delete Task",
        'menu_search': "4. Search Task",
        'menu_show': "5. Show All Tasks",
        'menu_pop': "6. Pop Last Task (LIFO)",
        'menu_exit': "0. Exit",
        'input_choice': "Choose an option: ",
        'insert_task_title': "\n-- Insert a New Task --",
        'task_title': "Task title: ",
        'task_due': "Due date (ex: YYYY-MM-DD): ",
        'task_priority': "Priority (Low/Medium/High): ",
        'task_desc': "Task description: ",  # Tambahan
        'task_added': "Task '{}' has been successfully added.",
        'motivation': "Motivation: ",
        'empty_cannot_update': "No tasks available, cannot update.",
        'update_title': "\n-- Update Task --",
        'input_index_update': "Enter the index of the task to update: ",
        'input_index_invalid': "Invalid input. Please enter a valid index number.",
        'task_updated': "Task has been updated.",
        'index_invalid': "Invalid index.",
        'delete_title': "\n-- Delete Task --",
        'input_index_delete': "Enter the index of the task to delete: ",
        'task_deleted': "Task has been deleted.",
        'search_title': "\n-- Search Tasks --",
        'input_search': "Enter a keyword (search in 'title' or 'due_date'): ",
        'search_result': "Search results:",
        'search_none': "No tasks match the given keyword.",
        'show_all': "\n-- All Tasks --",
        'pop_success': "Task '{}' has been popped from the stack.",
        'pop_empty': "Stack is empty, nothing to pop.",
        'exit_program': "Exiting the program. Have a great day!",
        'menu_invalid': "Invalid menu option. Please try again.",
        'index': "No",
        'title': "Title",
        'due_date': "Due Date",
        'priority': "Priority",
        'desc': "Description",        # Tambahan
        'no_tasks': "No tasks in the list."
    }
}
